'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property optBckgrd() As Short
            Get
                Return CType(Me("optBckgrd"),Short)
            End Get
            Set
                Me("optBckgrd") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property optClip() As Boolean
            Get
                Return CType(Me("optClip"),Boolean)
            End Get
            Set
                Me("optClip") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property optBigInt() As Boolean
            Get
                Return CType(Me("optBigInt"),Boolean)
            End Get
            Set
                Me("optBigInt") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property optBound() As Boolean
            Get
                Return CType(Me("optBound"),Boolean)
            End Get
            Set
                Me("optBound") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property optGlue() As Boolean
            Get
                Return CType(Me("optGlue"),Boolean)
            End Get
            Set
                Me("optGlue") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property optRndMethod() As Short
            Get
                Return CType(Me("optRndMethod"),Short)
            End Get
            Set
                Me("optRndMethod") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property optCheckUpdatesOnLoad() As Boolean
            Get
                Return CType(Me("optCheckUpdatesOnLoad"),Boolean)
            End Get
            Set
                Me("optCheckUpdatesOnLoad") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2.1")>  _
        Public Property version() As String
            Get
                Return CType(Me("version"),String)
            End Get
            Set
                Me("version") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property scrollErrorShown() As Boolean
            Get
                Return CType(Me("scrollErrorShown"),Boolean)
            End Get
            Set
                Me("scrollErrorShown") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property dictName() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("dictName"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("dictName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property dictNumWords() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("dictNumWords"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("dictNumWords") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property dictFirstLtrUp() As Boolean
            Get
                Return CType(Me("dictFirstLtrUp"),Boolean)
            End Get
            Set
                Me("dictFirstLtrUp") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property dictUseSpace() As Boolean
            Get
                Return CType(Me("dictUseSpace"),Boolean)
            End Get
            Set
                Me("dictUseSpace") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property dictUsePunc() As Boolean
            Get
                Return CType(Me("dictUsePunc"),Boolean)
            End Get
            Set
                Me("dictUsePunc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property dictDispStat() As Boolean
            Get
                Return CType(Me("dictDispStat"),Boolean)
            End Get
            Set
                Me("dictDispStat") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property dictAppendNoise() As Boolean
            Get
                Return CType(Me("dictAppendNoise"),Boolean)
            End Get
            Set
                Me("dictAppendNoise") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property dictDesc() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("dictDesc"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("dictDesc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property dictDir() As String
            Get
                Return CType(Me("dictDir"),String)
            End Get
            Set
                Me("dictDir") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property dictDirExists() As Boolean
            Get
                Return CType(Me("dictDirExists"),Boolean)
            End Get
            Set
                Me("dictDirExists") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property dictPath() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("dictPath"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("dictPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property optShowStatus() As Boolean
            Get
                Return CType(Me("optShowStatus"),Boolean)
            End Get
            Set
                Me("optShowStatus") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property dictUseAlliterations() As Boolean
            Get
                Return CType(Me("dictUseAlliterations"),Boolean)
            End Get
            Set
                Me("dictUseAlliterations") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property dictSize() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("dictSize"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("dictSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property dictFirstTime() As Boolean
            Get
                Return CType(Me("dictFirstTime"),Boolean)
            End Get
            Set
                Me("dictFirstTime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property dictThreadTask() As Boolean
            Get
                Return CType(Me("dictThreadTask"),Boolean)
            End Get
            Set
                Me("dictThreadTask") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property dictRndMethod() As Short
            Get
                Return CType(Me("dictRndMethod"),Short)
            End Get
            Set
                Me("dictRndMethod") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property srchHeavyStatistics() As Boolean
            Get
                Return CType(Me("srchHeavyStatistics"),Boolean)
            End Get
            Set
                Me("srchHeavyStatistics") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property firstTime() As Boolean
            Get
                Return CType(Me("firstTime"),Boolean)
            End Get
            Set
                Me("firstTime") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.RSG.My.MySettings
            Get
                Return Global.RSG.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
